sp:
  user-service:
    users: "[{\"id\":7, \"name\":\"abc\",\"password\":\"123\"},{\"id\":8, \"name\":\"def\",\"password\":\"456\"},{\"id\":9, \"name\":\"ghi\",\"password\":\"789\"},{\"id\":99, \"name\":\"whb\",\"password\":\"555\"}]"

spring:
  application:
    name: user-service
  cloud:
    config:
      override-none: true 
  rabbitmq: 
    host: 192.168.213.140 
    port: 5672 
    username: admin 
    password: admin        
server:
  port: 8101
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
management: 
  endpoints: 
    web:
      exposure: 
        include: refresh
        
        
        